# Generated by Django 6.0.2 on 2026-02-08 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Department Name')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': '01 - Departments',
                'db_table': 'app_auth_department',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Title Name')),
            ],
            options={
                'verbose_name': 'Title',
                'verbose_name_plural': '02 - Titles',
                'db_table': 'app_auth_title',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=50, verbose_name='Full Name')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photo/', verbose_name='Profile Photo')),
                ('phone_gsm', models.CharField(blank=True, max_length=12, null=True, verbose_name='Mobile Number')),
                ('phone_internal', models.CharField(blank=True, max_length=5, null=True, verbose_name='Internal Phone')),
                ('date_joined', models.DateField(auto_now=True, null=True, verbose_name='Join Date')),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='app_auth.department', verbose_name='Department')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='app_auth.title', verbose_name='Title')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': '03 - Users',
                'db_table': 'app_auth_accounts',
            },
        ),
    ]
